#!/bin/bash -x
#
# To make sure the example VCL code is valid and runnable, actually store the auth copy in
# the varnishtest files. Use the magic of sed to put it into the documentation.
#
tmpfile=/tmp/foo$RANDOM

DOCUMENT=INSTALL.rst

transform() {
    f=$1
    # stuff to put into the section
    sed -n '/varnish v1 -vcl+backend/,/start/p' tests/$f.vtc > $tmpfile
    sed -i 's/${projectdir}\/..\///' $tmpfile
    # remove first and last line of file. todo: learn more sed to do this more smoothly.
    tail -n+2 $tmpfile | head -n-1 > $tmpfile.2; mv $tmpfile.2 $tmpfile
    sed -e "/.. $f-start/ q" $DOCUMENT > $tmpfile.orig.top
    echo -e "\nVCL::\n" >> $tmpfile.orig.top
    sed -n "/.. $f-end/,\$p" $DOCUMENT >$tmpfile.orig.below
    cat $tmpfile.orig.top $tmpfile $tmpfile.orig.below > $DOCUMENT
    rm $tmpfile $tmpfile.orig.top $tmpfile.orig.below
}

transform 65-redir-mobile
transform 71-example1
transform 72-example2
transform 73-example3
